# ls-lint: File and directory naming conventions
# https://ls-lint.org

ls:
  # Global defaults (apply everywhere unless overridden by directory-specific rules)
  .dir: kebab-case
  .ts: kebab-case
  .js: kebab-case
  .json: kebab-case
  .yml: kebab-case
  .yaml: kebab-case
  .toml: kebab-case
  .md: 'regex:[A-Z][A-Z0-9-]*'

  # tests/: compound .test.ts extension + shell scripts
  tests:
    .test.ts: kebab-case
    .sh: kebab-case

  # examples/: kebab-case markdown and JSON (overrides global UPPERCASE .md)
  examples:
    .md: kebab-case
    .json: kebab-case

  # tasks/: kebab-case markdown (overrides global UPPERCASE .md)
  tasks:
    .md: kebab-case

  # workflows/: allow both kebab-case and UPPERCASE markdown
  workflows:
    .md: 'kebab-case | regex:[A-Z][A-Z0-9-]*'

  # .github/: CI workflow files
  .github:
    .yml: kebab-case
    .yaml: kebab-case

ignore:
  # Build artifacts and dependencies
  - node_modules
  - dist
  - .git

  # Tool/agent directories
  - .kittify
  - .opencode
  - .mise
  - .ralph-tui
  - .sisyphus
  - .ntm
  - .beads

  # Files with non-standard naming (dotted config, lockfiles, etc.)
  - eslint.config.js
  - bun.lock
  - hk.pkl
  - LICENSE
  - test.txt
  - 'session-*.md'
